// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("policy")
	ScopeName = "github.com/tero-platform/tero-collector-distro/processor/policyprocessor"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
