---
continue_on_error: true

regex_exclude:
  - '# yamlfmt: ignore'

# exclude:
#   - "example.yaml"

formatter:
  type: basic
  include_document_start: true
  retain_line_breaks_single: true
  trim_trailing_whitespace: true
  scan_folded_as_literal: true